### ISSUE TITLE
Build error - no method named `clone` found for struct `LevelOfDetail` in the current scope

### ISSUE THREAD

**Issue by rickyclarkson** [mrDIMAS/rusty-editor#3]
I am building in powershell using rustc and cargo 1.48.0, and git show shows c2620652b3aef6565c406e121e202fdd15aff02e, 'continue with lod editor'.

   Compiling rusty-editor v0.7.0 (C:\Users\ricky\rusty-editor)
error[E0599]: no method named `clone` found for struct `LevelOfDetail` in the current scope
    --> src\scene.rs:2291:30
     |
2291 |             .push(self.level.clone());
     |                              ^^^^^ method not found in `LevelOfDetail`
     |
    ::: C:\Users\ricky\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\clone.rs:119:8
     |
119  |     fn clone(&self) -> Self;
     |        -----
     |        |
     |        the method is available for `Arc<LevelOfDetail>` here
     |        the method is available for `Rc<LevelOfDetail>` here

error[E0599]: no method named `take_lod_group` found for mutable reference `&mut rg3d::scene::node::Node` in the current scope
    --> src\scene.rs:2992:31
     |
2992 |     get_set_swap!(self, node, take_lod_group, set_lod_group);
     |                               ^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `set_lod_group`

error[E0599]: no method named `clone` found for enum `Option<LodGroup>` in the current scope
    --> src\scene.rs:2948:39
     |
2948 |                 host.$set($self.value.clone());
     |                                       ^^^^^ method not found in `Option<LodGroup>`
...
2992 |     get_set_swap!(self, node, take_lod_group, set_lod_group);
     |     --------------------------------------------------------- in this macro invocation
     |
    ::: C:\Users\ricky\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\option.rs:158:1
     |
158  | pub enum Option<T> {
     | ------------------ doesn't satisfy `Option<LodGroup>: Clone`
     |
    ::: C:\Users\ricky\rg3d\src\scene\base.rs:145:1
     |
145  | pub struct LodGroup {
     | ------------------- doesn't satisfy `LodGroup: Clone`
     |
    ::: C:\Users\ricky\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\clone.rs:119:8
     |
119  |     fn clone(&self) -> Self;
     |        -----
     |        |
     |        the method is available for `Arc<Option<LodGroup>>` here
     |        the method is available for `Rc<Option<LodGroup>>` here
     |
     = note: the method `clone` exists but the following trait bounds were not satisfied:
             `LodGroup: Clone`
             which is required by `Option<LodGroup>: Clone`
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rusty-editor`

I did a git bisect and found that the bad commit was 2b65665a47ddfe95ef2e156f763e1bb0821baedd, started adding lod editor

**Comment by mrDIMAS** [comment]
Make sure you have latest rg3d near the editor.

**Comment by mrDIMAS** [comment]
It seems that everything works fine, closing the issue.
