### ISSUE TITLE
Unreachable reached in Render Path Dropdown List from Choosing Body Type Entry

### ISSUE THREAD

**Issue by MinusGix** [mrDIMAS/rusty-editor#4]
Rusty Editor Branch: Master latest (00d6f49ce6747c8cd063ef08b1c567e4362c7cc1)   
RG3D Branch: Master latest (4fa0422820619eef1dcafe2578d8c00cdaa62346)  
OS: Manjaro Arch Linux using i3  
Rustc Version: `rustc 1.48.0 (7eac88abb 2020-11-16)`, then I updated to `rustc 1.50.0 (cb75ad5db 2021-02-10)` and experienced the same issue.  
(Note: I doubt OS or Rustc version matter too much, but I included them just in case)

When changing the body type (following the tutorial, but building the editor myself) to Static or Kinematic, it hits the unreachable at https://github.com/mrDIMAS/rusty-editor/blob/00d6f49ce6747c8cd063ef08b1c567e4362c7cc1/src/sidebar/mesh.rs#L131 . If choosing None or Dynamic, it seems to behave correctly.  
I'm guessing this is due to it incorrectly receiving the selection (and thus number) from the Body dropdown, and thus that is an unreachable value for it. Though, since I have little understanding of the codebase, I'm not really sure *why* it does that.

**Comment by mrDIMAS** [comment]
Hi! I just forgot to check destination of a message. Anyway, fixed in [990862](https://github.com/mrDIMAS/rusty-editor/commit/990862fac37cd73d4356b49db07ec3116a66da95). Thanks!
